##############################################################################
# Copyright (c) 2017 Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
### LF POD 2 installer descriptor file ###

idf:
  version: 0.1
  fuel:
    jumphost:
      bridges:
        admin: 'pxebr'
        mgmt: 'br-ctl'
        private: ''
        public: ''
